### ISSUE TITLE
Support nested stages

### ISSUE THREAD

**Issue by dferber90** [dferber90/playroom-clickable-prototypes#2]
Let users nest stages so they don't have to copy the whole UI into the next frame if only a tiny part of the UI changes.

```jsx
<Stage id="stage-one" initial="start">
  <Frame stage="stage-one" id="start">
    <Stage id="stage-two" initial="frame-two">
      <Frame stage="stage-two" id="frame-two">
        <Trigger stage="stage-two" target="frame-two">next</Trigger>
      </Frame>
      <Frame stage="stage-two" id="frame-three">
        Stage two, Frame three
      </Frame>
    </Stage>
  </Frame>
</Stage>
```

This makes the API and implementation more difficult tho. Not sure it's worth it. If we go for it, the `stage` props need to be optional.

**Comment by VinSpee** [comment]
FWIW my gut is that this is overly-complicated and takes something away from the stark and scrappy feeling of copying stuff for a prototype

**Comment by dferber90** [comment]
Yeah, I got confused even trying to just write this example code. There's too much going on.

Maybe this would be work better

```jsx
<Stage initial="main/start">
  <Frame id="main/start">
    <Stage initial="user/signed-in">
      <Frame id="user/signed-in">
        <Trigger target="user/signed-out">next</Trigger>
      </Frame>
      <Frame id="user/signed-out">
        Stage two, Frame three
      </Frame>
    </Stage>
  </Frame>
</Stage>
```

We could parse the stage name from the `initial` prop, so it doesn't have to be declared twice.

We could make the prefix optional, so it would work as it is at the moment (single stage) and with nested stages.

But anyways, I want to see the need for it arise before actually going for it.
